apiVersion: apps/v1
kind: Deployment
metadata:
  name: none-non-serving
  labels:
     color: none
spec:
  replicas: 2
  selector:
    matchLabels:
      color: none
  template:
    metadata:
      labels:
        color: none
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: color
              operator: In
              values:
              - "none"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: hypershift.operator.io/serving-component
                operator: In
                values:
                - "true"
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      priorityClassName: low-priority
