apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-serving
  labels:
    color: blue
    hypershift.operator.io/serving-component: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      color: blue
      hypershift.operator.io/serving-component: "true"
  template:
    metadata:
      labels:
        color: blue
        hypershift.operator.io/serving-component: "true"
    spec:
      tolerations:
        - key: "hypershift.operator.io/serving-component"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: color
              operator: In
              values:
              - "blue"
            - key: hypershift.operator.io/serving-component
              operator: In
              values:
              - "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: hypershift.operator.io/serving-component
                operator: In
                values:
                - "true"
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      priorityClassName: preempting-high-priority
