apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-non-serving
  labels:
     color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: color
              operator: In
              values:
              - "blue"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: hypershift.operator.io/serving-component
                operator: In
                values:
                - "true"
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      priorityClassName: preempting-high-priority
