apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-non-serving
  labels:
     color: none-non-serving
spec:
  replicas: 2
  selector:
    matchLabels:
      color: none-non-serving
  template:
    metadata:
      labels:
        color: none-non-serving
    spec:
      affinity:
        nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: hypershift.operator.io/serving-component
                 operator: NotIn
                 values:
                   - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: color
                operator: In
                values:
                - none-non-serving
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: pause
        image: registry.k8s.io/pause
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      priorityClassName: low-priority
