apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-serving
  labels:
    color: none-serving
    hypershift.operator.io/serving-component: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      color: none-serving
      hypershift.operator.io/serving-component: "true"
  template:
    metadata:
      labels:
        color: none-serving
        hypershift.operator.io/serving-component: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: hypershift.operator.io/serving-component
                operator: In
                values:
                - "true"
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: color
                operator: In
                values:
                - none-serving
            topologyKey: topology.kubernetes.io/zone
      nodeSelector:
        hypershift.operator.io/serving-component: "true"
      containers:
      - name: pause
        image: registry.k8s.io/pause
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      priorityClassName: low-priority
